#! /bin/bash
# FS QA Test No. 244
#
# test to verify that proper project quota id is correctly set
#
#-----------------------------------------------------------------------
# Copyright (c) 2010 Arkadiusz Miśkiewicz.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#-----------------------------------------------------------------------
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/quota

_cleanup()
{
	cd /
	umount $SCRATCH_MNT 2>/dev/null
	rm -f $tmp.*
}

# real QA test starts here
_supported_fs ext4
_require_xfs_quota
_require_scratch

# make fs with no projid32bit
_scratch_mkfs_ext4 -O quota,project >> $seqres.full 2>&1 || _fail "mkfs failed"
_scratch_mount

dir=$SCRATCH_MNT/project

status=0

echo "Silence is golden"

mkdir $dir

touch $dir/below16bit
# below 16bit value
src/setproject -v 3422 $dir/below16bit
projid=$(src/getproject --only-values $dir/below16bit)
if [ "3422" != "$projid" ]; then
	echo "FAIL: returned projid value ($projid)"
	echo "      doesn't match set one (projid = 3422)"
	status=1
fi

# 32bit value, should succeed
touch $dir/over16bit
if src/setproject -v 108545 $dir/over16bit \
		>> $seqres.full 2>&1; then
	projid=$(src/getproject --only-values $dir/over16bit)
	if [ "108545" != "$projid" ]; then
		echo "FAIL: returned projid value ($projid)"
		echo "      doesn't match set one (projid = 108545)"
		status=1
	fi
else
	echo "FAIL: setting 32bit projid failed"
	echo "      while it should succeed"
	status=1
fi

# over 32bit value, should fail
# currently it is setproject bug...anyway....
touch $dir/over32bit
if src/setproject -v 5344967296  $dir/over16bit \
		>> $seqres.full 2>&1; then
	projid=$(src/getproject --only-values $dir/over16bit)
	if [ "5344967296" == "$projid" ]; then
		echo "FAIL: setting 32bit projid failed"
		echo "      while it should succeed"
		status=1
	fi
else
	status=1
fi
